### ISSUE TITLE
Too Many Cooks

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/aardcogs#104]
If there are too many collaborators an error happens: https://untappd.com/b/vandestreek-bier-body-and-soul/3049424 is a test beer.

```
[29/01/2019 19:27] ERROR red on_command_error 369: Exception in command 'findbeer'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/opt/red/cogs/untappd.py", line 648, in findbeer
    message = await self.bot.say(resultStr, embed=embed)
  File "lib/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "/opt/red/red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
```

**Comment by AardWolf** [comment]
Fixed in #105
