### ISSUE TITLE
profile with mention broken in v3 code

### ISSUE THREAD

**Issue by AardWolf** [AardWolf/aardcogs#145]
```
[2019-09-10 18:26:55] [ERROR] red: Exception in command 'profile'
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/opt/untappdCog/aardcogs-redbot-upgrade/untappd/untappd.py", line 672, in profile
    if ctx.message.server:
AttributeError: 'Message' object has no attribute 'server'
```

**Comment by AardWolf** [comment]
#146 
Fixed!
